---
name: clash-verge

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/build.yml
      - build.sh
  schedule:
    - cron: 0 23 * * *

permissions: write-all
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: check if we need to trigger a build
        id: check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION=$(gh api /repos/clash-verge-rev/clash-verge-rev/releases/latest --jq '.tag_name')
          echo "version=$VERSION" >> "$GITHUB_ENV"
          if ! wget --spider "https://github.com/${{github.repository}}/releases/download/$VERSION/clash-verge-${VERSION}-x86_64.AppImage" > /dev/null 2>&1; then
          echo "trigger=true" >> "$GITHUB_ENV"
          echo "Build $VERSION"
          else
          echo "trigger=false" >> "$GITHUB_ENV"
          echo "Skip $VERSION"
          fi
          if [ -z $VERSION ]; then
          echo "trigger=false" >> "$GITHUB_ENV"
          echo "No version found"
          fi

      - name: checkout
        if: env.trigger == 'true'
        uses: actions/checkout@main

      - name: build
        if: env.trigger == 'true'
        env:
          VERSION: ${{ env.version }}
        run: |
          sudo apt update
          sudo apt install libfuse2
          bash build.sh
          cp "clash-verge-${VERSION}-x86_64.tar.xz" "clash-verge-x86_64.tar.xz"
          cp "clash-verge-${VERSION}-x86_64.AppImage" "clash-verge-x86_64.AppImage"
          shasum -a 1 clash-verge-* > SHA1SUMS

      - name: create release note
        if: env.trigger == 'true'
        run: |
          echo "Build date: $(date '+%Y-%m-%d %H:%M:%S')" > note.md
          echo '### SHA1 Checksums' >> note.md
          echo '```' >> note.md  # Do not use double quotes
          cat SHA1SUMS >> note.md
          echo '```' >> note.md
          cat note.md

      - name: release
        if: env.trigger == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ env.version }}
        run: |
          gh release create "${VERSION}" --notes-file note.md --title "Clash Verge ${VERSION}" --repo "${{github.repository}}" || true
          gh release upload "${VERSION}" "clash-verge-${VERSION}-x86_64.AppImage" --clobber --repo "${{github.repository}}"
          gh release upload "${VERSION}" "clash-verge-${VERSION}-x86_64.tar.xz" --clobber --repo "${{github.repository}}"
          gh release upload "${VERSION}" ./SHA1SUMS --clobber --repo "${{github.repository}}"

          gh release create "stable" --prerelease --notes-file note.md --title "Clash Verge ${VERSION}" --repo "${{github.repository}}" || true
          gh release edit "stable" --prerelease --notes-file note.md --title "Clash Verge ${VERSION}" --repo "${{github.repository}}" || true
          gh release upload "stable" "clash-verge-x86_64.AppImage" --clobber --repo "${{github.repository}}"
          gh release upload "stable" "clash-verge-x86_64.tar.xz" --clobber --repo "${{github.repository}}"
          gh release upload "${VERSION}" ./SHA1SUMS --clobber --repo "${{github.repository}}"

  keepalive-job:
    name: Keepalive Workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: gautamkrishnar/keepalive-workflow@v2
